package com.tonya.dzcscale;

import android.os.Bundle;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;

/**
 * Required by Health Connect so the user can see how this app uses health permissions.
 * The app writes only measurements generated by the DZC-D18E3 workflow after a completed measurement is saved manually or through the optional auto-sync setting.
 */
public class HealthPermissionsRationaleActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        ScrollView scroll = new ScrollView(this);
        LinearLayout content = new LinearLayout(this);
        content.setOrientation(LinearLayout.VERTICAL);
        int pad = (int) (24 * getResources().getDisplayMetrics().density);
        content.setPadding(pad, pad, pad, pad);

        TextView title = new TextView(this);
        title.setTextSize(24);
        title.setText("DZC Scale Health and Health Connect");
        content.addView(title);

        TextView body = new TextView(this);
        body.setTextSize(16);
        body.setPadding(0, pad, 0, 0);
        body.setText(
                "DZC Scale Health requests permission to write the measurements you explicitly choose to save.\n\n" +
                "Data written to Health Connect:\n" +
                "• Weight\n" +
                "• Estimated body fat percentage\n" +
                "• Estimated lean body mass\n" +
                "• Estimated body water mass\n" +
                "• Estimated basal metabolic rate\n\n" +
                "Weight is measured directly by the DZC-D18E3 scale. The other values are estimates calculated from weight, foot-to-foot impedance, height, age, and sex using the app's documented algorithm.\n\n" +
                "The app does not read your existing Health Connect data. It does not automatically sync in the background. A measurement is written only when you tap Save to Health Connect."
        );
        content.addView(body);

        scroll.addView(content);
        setContentView(scroll);
    }
}
